$('.HistoBroadlink').on('click',function(){ graph('Broadlink', 17695); });
	$('.HistoCam-Bureau').on('click',function(){ graph('Cam Bureau', 17706); });
	$('.HistoCam-Doorbird').on('click',function(){ graph('Cam Doorbird', 19026); });
	$('.HistoCam-Entrée').on('click',function(){ graph('Cam Entrée', 19407); });
	$('.HistoCam-Piscine').on('click',function(){ graph('Cam Piscine', 17684); });
	$('.HistoCam-SàM').on('click',function(){ graph('Cam SàM', 17717); });
	$('.HistoESXi').on('click',function(){ graph('ESXi', 17618); });
	$('.HistoEX7000').on('click',function(){ graph('EX7000', 17587); });
	$('.HistoFrame-TV').on('click',function(){ graph('Frame TV', 20538); });
	$('.HistoGoogle-Home').on('click',function(){ graph('Google-Home', 18357); });
	$('.HistoICO-ONDILO').on('click',function(){ graph('ICO-ONDILO', 17772); });
	$('.HistoJPI').on('click',function(){ graph('JPI', 17640); });
	$('.HistoJeedom').on('click',function(){ graph('Jeedom', 22431); });
	$('.HistoLampe-Oeuf').on('click',function(){ graph('Lampe Oeuf', 17739); });
	$('.HistoPC-MG').on('click',function(){ graph('PC-MG', 23689); });
	$('.HistoPC-Mamina').on('click',function(){ graph('PC-Mamina', 17565); });
	$('.HistoPC-NR').on('click',function(){ graph('PC-NR', 17554); });
	$('.HistoSonosD').on('click',function(){ graph('SonosD', 17801); });
	$('.HistoSonosG').on('click',function(){ graph('SonosG', 17823); });
	$('.HistoTablette-NR').on('click',function(){ graph('Tablette-NR', 17629); });
	$('.HistoTel-MG').on('click',function(){ graph('Tel-MG', 17576); });
	$('.HistoTel-MS').on('click',function(){ graph('Tel-MS', 19868); });
	$('.HistoTel-NR').on('click',function(){ graph('Tel-NR', 20478); });
	$('.HistoTel-PS').on('click',function(){ graph('Tel-PS', 19134); });
	$('.HistoWithing').on('click',function(){ graph('Withing', 17894); });
	$('.HistoXiaomi-1').on('click',function(){ graph('Xiaomi-1', 17728); });
	$('.HistoXiaomi-2').on('click',function(){ graph('Xiaomi-2', 17883); });
	